const express=require("express");
const router=express.Router();

router.get('/',async(req,res)=>{
    const Story={
        "storyTitle": "Learning Process of My Early Childhood",
        "story": "In the month of January, 1973, it is the year when I began to have a deep memories that I can still clearly remember until now. It is the year when I started my schooling days at a small primary school which was built and started by the christian evangelical since 1800 something. The school name is \"Holy Name Primary School\", which still exist until today. This school consist of 4 rooms. 3 rooms for classroom, and another room for the teachers. During my time at the primary school, the intake is alternately, once in two years. \n I started my formal learning not in my mother tongue language, nor in our national language, but purely in English. I started to pronounce alphabeth, words and numbers in English. In primary school, I some how create a bit of history, that is since primary one until primary six, I behold to the number One when ever we have our school exam. The sad thing is, as far as I remember, my parents never seem to have acknowledge my good achivement. As to me, this achivement also mean nothing more than just a routine in school, that mean I don't care and bother much to it. Asked me now , I don't have an answer to it. \n It's a hard time during my primary school days. Everday I have to walks about two miles to school, on a gravel road, as early as 6.00 am in the morning, and return home around two or three in the afternoon. The funny things is, I never have my lunch box to school, although in the morning I'll only have a cup of coffee. Shoes, I never dream of it, because my parents can only afford a simple rubber slippers, and when the slippers torn apart, that mean I have to be bare footed to school. Belt, nice to have one, but the reality I never have. The only belt that I know to tighten my school shorts is a plastic string. School beg, unfortunately I don't have the knowledge about it too. I always put my school books in a plastic beg, tug inside at the backside of my school white shirt and tied the end parts of my school shirt tightly, off I go. \n That the reality of my primary school life. I don't regret it, because I now know that I am always grateful for what I have and I treasured it most. I learned a lot from this simple way of acquiring a formal education. I will never blamed my parents for what I have experience, because I know that the best they can give me. I am grateful to them because they are the one to give me the chance to live in this beautiful world. creation of the Almighty God."
    };
    res.json(Story);
});

module.exports=router;